//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.16.0
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""7c05bff2-6e24-4f52-b09b-affc729ef851"",
            ""actions"": [
                {
                    ""name"": ""Player_Forward"",
                    ""type"": ""Button"",
                    ""id"": ""73675d90-bb08-4289-8f59-19aca8fee1cf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_Backward"",
                    ""type"": ""Button"",
                    ""id"": ""a3bc96bd-4f5b-4565-9d3f-cb628739df65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_Right"",
                    ""type"": ""Button"",
                    ""id"": ""7d1080e4-bf91-43e4-9799-84bc5e72fd6e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_Left"",
                    ""type"": ""Button"",
                    ""id"": ""db229a4b-7a26-49ef-ad58-bae6dcdcf0b9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_Walk"",
                    ""type"": ""Button"",
                    ""id"": ""6a5ccc9c-0048-445f-b240-a4e9af18b94a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_Collect"",
                    ""type"": ""Button"",
                    ""id"": ""aa84c321-1041-4c8e-a281-256f702881d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""6fab571a-c400-46d4-a384-62a800a4fc34"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Player_Fishing"",
                    ""type"": ""Button"",
                    ""id"": ""91ae4b3b-6b36-4334-8d2e-670051229f0b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_Cast"",
                    ""type"": ""Button"",
                    ""id"": ""57770573-4289-43e6-a692-819d1d699b59"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_FishingMinigame_Arrow_Up"",
                    ""type"": ""Button"",
                    ""id"": ""3bb38824-2f5c-41c5-b0cd-1bf9604db142"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_FishingMinigame_Arrow_Right"",
                    ""type"": ""Button"",
                    ""id"": ""7dbf2eee-d355-4c42-884f-977e851a0a19"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_FishingMinigame_Arrow_Down"",
                    ""type"": ""Button"",
                    ""id"": ""ce452295-ee11-4b3e-87ee-d5535e3d5999"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player_FishingMinigame_Arrow_Left"",
                    ""type"": ""Button"",
                    ""id"": ""eec6de91-1441-4488-b37b-e4395c6a4398"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4c43a08-9703-41e6-9344-1885ab13657a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d6293b6-c915-4298-846e-a0c50f3d1c78"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0e8a353-a6bd-4862-bfdc-83d57bdfe973"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09b7e3e1-016e-49de-9a8c-051f07e6f96b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eabe0509-b871-4660-ae94-7cecf5c9ad55"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddeb5a45-5325-4e02-85df-ff74d9af82f7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Collect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6097bbd3-075f-42b2-950d-0a2269ff3694"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""29a421b0-7d73-41e7-91ef-948d68f217a2"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Fishing"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7eabd59e-ed55-4b1c-85cd-f3f1f123131f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Fishing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""72fd2aee-a033-492e-8319-01ed297eb08d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Fishing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""abce99c2-b01a-43dc-8162-e21b4ffbe71a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_Cast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52bffa33-e893-419c-af6c-ace7382db0b2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_FishingMinigame_Arrow_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf636853-85a6-468f-a405-0d5f387ebfe4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_FishingMinigame_Arrow_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25d82f4d-90a9-4bef-b641-89e5b68ff897"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_FishingMinigame_Arrow_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27de6bcc-252f-4d32-a64a-49cade95b534"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player_FishingMinigame_Arrow_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""5bbfab05-3ddc-4418-bb0e-7d1f1cdda9e6"",
            ""actions"": [
                {
                    ""name"": ""UI_Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""3228cdd6-7dac-4848-9353-78ca350883b4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Close"",
                    ""type"": ""Button"",
                    ""id"": ""993fb04a-a42f-445f-bfbd-bce823d13e19"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Fishing_Minigame"",
                    ""type"": ""Button"",
                    ""id"": ""4b881e03-adf6-4124-8cd4-2b57168cb60b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""65977b2d-a65c-4af3-8d07-e245383d5278"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6123537e-fb42-4a5f-99d5-11fd8bf8575f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2d43718-ff4e-4666-b593-4d6792a24033"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Fishing_Minigame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Player_Forward = m_Player.FindAction("Player_Forward", throwIfNotFound: true);
        m_Player_Player_Backward = m_Player.FindAction("Player_Backward", throwIfNotFound: true);
        m_Player_Player_Right = m_Player.FindAction("Player_Right", throwIfNotFound: true);
        m_Player_Player_Left = m_Player.FindAction("Player_Left", throwIfNotFound: true);
        m_Player_Player_Walk = m_Player.FindAction("Player_Walk", throwIfNotFound: true);
        m_Player_Player_Collect = m_Player.FindAction("Player_Collect", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Player_Fishing = m_Player.FindAction("Player_Fishing", throwIfNotFound: true);
        m_Player_Player_Cast = m_Player.FindAction("Player_Cast", throwIfNotFound: true);
        m_Player_Player_FishingMinigame_Arrow_Up = m_Player.FindAction("Player_FishingMinigame_Arrow_Up", throwIfNotFound: true);
        m_Player_Player_FishingMinigame_Arrow_Right = m_Player.FindAction("Player_FishingMinigame_Arrow_Right", throwIfNotFound: true);
        m_Player_Player_FishingMinigame_Arrow_Down = m_Player.FindAction("Player_FishingMinigame_Arrow_Down", throwIfNotFound: true);
        m_Player_Player_FishingMinigame_Arrow_Left = m_Player.FindAction("Player_FishingMinigame_Arrow_Left", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_UI_Inventory = m_UI.FindAction("UI_Inventory", throwIfNotFound: true);
        m_UI_UI_Close = m_UI.FindAction("UI_Close", throwIfNotFound: true);
        m_UI_UI_Fishing_Minigame = m_UI.FindAction("UI_Fishing_Minigame", throwIfNotFound: true);
    }

    ~@InputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputActions.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, InputActions.UI.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Player_Forward;
    private readonly InputAction m_Player_Player_Backward;
    private readonly InputAction m_Player_Player_Right;
    private readonly InputAction m_Player_Player_Left;
    private readonly InputAction m_Player_Player_Walk;
    private readonly InputAction m_Player_Player_Collect;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Player_Fishing;
    private readonly InputAction m_Player_Player_Cast;
    private readonly InputAction m_Player_Player_FishingMinigame_Arrow_Up;
    private readonly InputAction m_Player_Player_FishingMinigame_Arrow_Right;
    private readonly InputAction m_Player_Player_FishingMinigame_Arrow_Down;
    private readonly InputAction m_Player_Player_FishingMinigame_Arrow_Left;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Forward".
        /// </summary>
        public InputAction @Player_Forward => m_Wrapper.m_Player_Player_Forward;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Backward".
        /// </summary>
        public InputAction @Player_Backward => m_Wrapper.m_Player_Player_Backward;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Right".
        /// </summary>
        public InputAction @Player_Right => m_Wrapper.m_Player_Player_Right;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Left".
        /// </summary>
        public InputAction @Player_Left => m_Wrapper.m_Player_Player_Left;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Walk".
        /// </summary>
        public InputAction @Player_Walk => m_Wrapper.m_Player_Player_Walk;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Collect".
        /// </summary>
        public InputAction @Player_Collect => m_Wrapper.m_Player_Player_Collect;
        /// <summary>
        /// Provides access to the underlying input action "Player/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Player_Look;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Fishing".
        /// </summary>
        public InputAction @Player_Fishing => m_Wrapper.m_Player_Player_Fishing;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_Cast".
        /// </summary>
        public InputAction @Player_Cast => m_Wrapper.m_Player_Player_Cast;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_FishingMinigame_Arrow_Up".
        /// </summary>
        public InputAction @Player_FishingMinigame_Arrow_Up => m_Wrapper.m_Player_Player_FishingMinigame_Arrow_Up;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_FishingMinigame_Arrow_Right".
        /// </summary>
        public InputAction @Player_FishingMinigame_Arrow_Right => m_Wrapper.m_Player_Player_FishingMinigame_Arrow_Right;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_FishingMinigame_Arrow_Down".
        /// </summary>
        public InputAction @Player_FishingMinigame_Arrow_Down => m_Wrapper.m_Player_Player_FishingMinigame_Arrow_Down;
        /// <summary>
        /// Provides access to the underlying input action "Player/Player_FishingMinigame_Arrow_Left".
        /// </summary>
        public InputAction @Player_FishingMinigame_Arrow_Left => m_Wrapper.m_Player_Player_FishingMinigame_Arrow_Left;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Player_Forward.started += instance.OnPlayer_Forward;
            @Player_Forward.performed += instance.OnPlayer_Forward;
            @Player_Forward.canceled += instance.OnPlayer_Forward;
            @Player_Backward.started += instance.OnPlayer_Backward;
            @Player_Backward.performed += instance.OnPlayer_Backward;
            @Player_Backward.canceled += instance.OnPlayer_Backward;
            @Player_Right.started += instance.OnPlayer_Right;
            @Player_Right.performed += instance.OnPlayer_Right;
            @Player_Right.canceled += instance.OnPlayer_Right;
            @Player_Left.started += instance.OnPlayer_Left;
            @Player_Left.performed += instance.OnPlayer_Left;
            @Player_Left.canceled += instance.OnPlayer_Left;
            @Player_Walk.started += instance.OnPlayer_Walk;
            @Player_Walk.performed += instance.OnPlayer_Walk;
            @Player_Walk.canceled += instance.OnPlayer_Walk;
            @Player_Collect.started += instance.OnPlayer_Collect;
            @Player_Collect.performed += instance.OnPlayer_Collect;
            @Player_Collect.canceled += instance.OnPlayer_Collect;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Player_Fishing.started += instance.OnPlayer_Fishing;
            @Player_Fishing.performed += instance.OnPlayer_Fishing;
            @Player_Fishing.canceled += instance.OnPlayer_Fishing;
            @Player_Cast.started += instance.OnPlayer_Cast;
            @Player_Cast.performed += instance.OnPlayer_Cast;
            @Player_Cast.canceled += instance.OnPlayer_Cast;
            @Player_FishingMinigame_Arrow_Up.started += instance.OnPlayer_FishingMinigame_Arrow_Up;
            @Player_FishingMinigame_Arrow_Up.performed += instance.OnPlayer_FishingMinigame_Arrow_Up;
            @Player_FishingMinigame_Arrow_Up.canceled += instance.OnPlayer_FishingMinigame_Arrow_Up;
            @Player_FishingMinigame_Arrow_Right.started += instance.OnPlayer_FishingMinigame_Arrow_Right;
            @Player_FishingMinigame_Arrow_Right.performed += instance.OnPlayer_FishingMinigame_Arrow_Right;
            @Player_FishingMinigame_Arrow_Right.canceled += instance.OnPlayer_FishingMinigame_Arrow_Right;
            @Player_FishingMinigame_Arrow_Down.started += instance.OnPlayer_FishingMinigame_Arrow_Down;
            @Player_FishingMinigame_Arrow_Down.performed += instance.OnPlayer_FishingMinigame_Arrow_Down;
            @Player_FishingMinigame_Arrow_Down.canceled += instance.OnPlayer_FishingMinigame_Arrow_Down;
            @Player_FishingMinigame_Arrow_Left.started += instance.OnPlayer_FishingMinigame_Arrow_Left;
            @Player_FishingMinigame_Arrow_Left.performed += instance.OnPlayer_FishingMinigame_Arrow_Left;
            @Player_FishingMinigame_Arrow_Left.canceled += instance.OnPlayer_FishingMinigame_Arrow_Left;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Player_Forward.started -= instance.OnPlayer_Forward;
            @Player_Forward.performed -= instance.OnPlayer_Forward;
            @Player_Forward.canceled -= instance.OnPlayer_Forward;
            @Player_Backward.started -= instance.OnPlayer_Backward;
            @Player_Backward.performed -= instance.OnPlayer_Backward;
            @Player_Backward.canceled -= instance.OnPlayer_Backward;
            @Player_Right.started -= instance.OnPlayer_Right;
            @Player_Right.performed -= instance.OnPlayer_Right;
            @Player_Right.canceled -= instance.OnPlayer_Right;
            @Player_Left.started -= instance.OnPlayer_Left;
            @Player_Left.performed -= instance.OnPlayer_Left;
            @Player_Left.canceled -= instance.OnPlayer_Left;
            @Player_Walk.started -= instance.OnPlayer_Walk;
            @Player_Walk.performed -= instance.OnPlayer_Walk;
            @Player_Walk.canceled -= instance.OnPlayer_Walk;
            @Player_Collect.started -= instance.OnPlayer_Collect;
            @Player_Collect.performed -= instance.OnPlayer_Collect;
            @Player_Collect.canceled -= instance.OnPlayer_Collect;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Player_Fishing.started -= instance.OnPlayer_Fishing;
            @Player_Fishing.performed -= instance.OnPlayer_Fishing;
            @Player_Fishing.canceled -= instance.OnPlayer_Fishing;
            @Player_Cast.started -= instance.OnPlayer_Cast;
            @Player_Cast.performed -= instance.OnPlayer_Cast;
            @Player_Cast.canceled -= instance.OnPlayer_Cast;
            @Player_FishingMinigame_Arrow_Up.started -= instance.OnPlayer_FishingMinigame_Arrow_Up;
            @Player_FishingMinigame_Arrow_Up.performed -= instance.OnPlayer_FishingMinigame_Arrow_Up;
            @Player_FishingMinigame_Arrow_Up.canceled -= instance.OnPlayer_FishingMinigame_Arrow_Up;
            @Player_FishingMinigame_Arrow_Right.started -= instance.OnPlayer_FishingMinigame_Arrow_Right;
            @Player_FishingMinigame_Arrow_Right.performed -= instance.OnPlayer_FishingMinigame_Arrow_Right;
            @Player_FishingMinigame_Arrow_Right.canceled -= instance.OnPlayer_FishingMinigame_Arrow_Right;
            @Player_FishingMinigame_Arrow_Down.started -= instance.OnPlayer_FishingMinigame_Arrow_Down;
            @Player_FishingMinigame_Arrow_Down.performed -= instance.OnPlayer_FishingMinigame_Arrow_Down;
            @Player_FishingMinigame_Arrow_Down.canceled -= instance.OnPlayer_FishingMinigame_Arrow_Down;
            @Player_FishingMinigame_Arrow_Left.started -= instance.OnPlayer_FishingMinigame_Arrow_Left;
            @Player_FishingMinigame_Arrow_Left.performed -= instance.OnPlayer_FishingMinigame_Arrow_Left;
            @Player_FishingMinigame_Arrow_Left.canceled -= instance.OnPlayer_FishingMinigame_Arrow_Left;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_UI_Inventory;
    private readonly InputAction m_UI_UI_Close;
    private readonly InputAction m_UI_UI_Fishing_Minigame;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI".
    /// </summary>
    public struct UIActions
    {
        private @InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI/UI_Inventory".
        /// </summary>
        public InputAction @UI_Inventory => m_Wrapper.m_UI_UI_Inventory;
        /// <summary>
        /// Provides access to the underlying input action "UI/UI_Close".
        /// </summary>
        public InputAction @UI_Close => m_Wrapper.m_UI_UI_Close;
        /// <summary>
        /// Provides access to the underlying input action "UI/UI_Fishing_Minigame".
        /// </summary>
        public InputAction @UI_Fishing_Minigame => m_Wrapper.m_UI_UI_Fishing_Minigame;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIActions" />
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @UI_Inventory.started += instance.OnUI_Inventory;
            @UI_Inventory.performed += instance.OnUI_Inventory;
            @UI_Inventory.canceled += instance.OnUI_Inventory;
            @UI_Close.started += instance.OnUI_Close;
            @UI_Close.performed += instance.OnUI_Close;
            @UI_Close.canceled += instance.OnUI_Close;
            @UI_Fishing_Minigame.started += instance.OnUI_Fishing_Minigame;
            @UI_Fishing_Minigame.performed += instance.OnUI_Fishing_Minigame;
            @UI_Fishing_Minigame.canceled += instance.OnUI_Fishing_Minigame;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIActions" />
        private void UnregisterCallbacks(IUIActions instance)
        {
            @UI_Inventory.started -= instance.OnUI_Inventory;
            @UI_Inventory.performed -= instance.OnUI_Inventory;
            @UI_Inventory.canceled -= instance.OnUI_Inventory;
            @UI_Close.started -= instance.OnUI_Close;
            @UI_Close.performed -= instance.OnUI_Close;
            @UI_Close.canceled -= instance.OnUI_Close;
            @UI_Fishing_Minigame.started -= instance.OnUI_Fishing_Minigame;
            @UI_Fishing_Minigame.performed -= instance.OnUI_Fishing_Minigame;
            @UI_Fishing_Minigame.canceled -= instance.OnUI_Fishing_Minigame;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIActions.UnregisterCallbacks(IUIActions)" />.
        /// </summary>
        /// <seealso cref="UIActions.UnregisterCallbacks(IUIActions)" />
        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIActions.AddCallbacks(IUIActions)" />
        /// <seealso cref="UIActions.RemoveCallbacks(IUIActions)" />
        /// <seealso cref="UIActions.UnregisterCallbacks(IUIActions)" />
        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIActions" /> instance referencing this action map.
    /// </summary>
    public UIActions @UI => new UIActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Player_Forward" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Forward(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Backward" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Backward(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Right(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Left(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Walk" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Walk(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Collect" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Collect(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Fishing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Fishing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_Cast" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_Cast(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_FishingMinigame_Arrow_Up" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_FishingMinigame_Arrow_Up(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_FishingMinigame_Arrow_Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_FishingMinigame_Arrow_Right(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_FishingMinigame_Arrow_Down" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_FishingMinigame_Arrow_Down(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Player_FishingMinigame_Arrow_Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayer_FishingMinigame_Arrow_Left(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIActions.AddCallbacks(IUIActions)" />
    /// <seealso cref="UIActions.RemoveCallbacks(IUIActions)" />
    public interface IUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "UI_Inventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUI_Inventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UI_Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUI_Close(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UI_Fishing_Minigame" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUI_Fishing_Minigame(InputAction.CallbackContext context);
    }
}
